// ── Theme Definitions ──────────────────────────────────────────────────────
// Each theme defines both UI surface colors and a full xterm 16-color palette.

export interface TerminalColors {
  background: string;
  foreground: string;
  cursor: string;
  selectionBackground: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

export interface ThemeColors {
  // UI surface colors
  bg: string;
  bgPanel: string;
  bgTerminal: string;
  bgHover: string;
  bgInput: string;
  bgSectionHeader: string;
  border: string;
  text: string;
  textMuted: string;
  textDimmed: string;
  primary: string;
  primaryHover: string;
  scrollThumb: string;
  accent: string;
  // Terminal 16-color ANSI palette
  terminal: TerminalColors;
}

export interface Theme {
  id: string;
  name: string;
  /** Short label for the switcher preview */
  label: string;
  /** Representative color swatch for the picker */
  swatch: string;
  colors: ThemeColors;
}

// ── GitHub Dark ────────────────────────────────────────────────────────────
const githubDark: Theme = {
  id: "github-dark",
  name: "GitHub Dark",
  label: "GitHub",
  swatch: "#0d1117",
  colors: {
    bg: "#0d1117",
    bgPanel: "#161b22",
    bgTerminal: "#0d1117",
    bgHover: "#1c2128",
    bgInput: "#0d1117",
    bgSectionHeader: "#12171f",
    border: "#30363d",
    text: "#c9d1d9",
    textMuted: "#8b949e",
    textDimmed: "#6e7681",
    primary: "#3b82f6",
    primaryHover: "#2563eb",
    scrollThumb: "#30363d",
    accent: "#58a6ff",
    terminal: {
      background: "#0d1117",
      foreground: "#c9d1d9",
      cursor: "#c9d1d9",
      selectionBackground: "#264f78",
      black: "#484f58",
      red: "#ff7b72",
      green: "#3fb950",
      yellow: "#d29922",
      blue: "#58a6ff",
      magenta: "#bc8cff",
      cyan: "#39d353",
      white: "#b1bac4",
      brightBlack: "#6e7681",
      brightRed: "#ffa198",
      brightGreen: "#56d364",
      brightYellow: "#e3b341",
      brightBlue: "#79c0ff",
      brightMagenta: "#d2a8ff",
      brightCyan: "#56d364",
      brightWhite: "#f0f6fc",
    },
  },
};

// ── Dracula ────────────────────────────────────────────────────────────────
const dracula: Theme = {
  id: "dracula",
  name: "Dracula",
  label: "Dracula",
  swatch: "#282a36",
  colors: {
    bg: "#282a36",
    bgPanel: "#21222c",
    bgTerminal: "#282a36",
    bgHover: "#343746",
    bgInput: "#21222c",
    bgSectionHeader: "#303341",
    border: "#44475a",
    text: "#f8f8f2",
    textMuted: "#bd93f9",
    textDimmed: "#6272a4",
    primary: "#bd93f9",
    primaryHover: "#a77bfa",
    scrollThumb: "#44475a",
    accent: "#ff79c6",
    terminal: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
};

// ── Nord ───────────────────────────────────────────────────────────────────
const nord: Theme = {
  id: "nord",
  name: "Nord",
  label: "Nord",
  swatch: "#2e3440",
  colors: {
    bg: "#2e3440",
    bgPanel: "#3b4252",
    bgTerminal: "#2e3440",
    bgHover: "#434c5e",
    bgInput: "#2e3440",
    bgSectionHeader: "#323845",
    border: "#4c566a",
    text: "#d8dee9",
    textMuted: "#81a1c1",
    textDimmed: "#616e88",
    primary: "#88c0d0",
    primaryHover: "#7bb8c9",
    scrollThumb: "#4c566a",
    accent: "#5e81ac",
    terminal: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      selectionBackground: "#434c5e",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#d06f79",
      brightGreen: "#b1cc99",
      brightYellow: "#f1d59d",
      brightBlue: "#93b4d6",
      brightMagenta: "#c59cbd",
      brightCyan: "#9bd3e4",
      brightWhite: "#eceff4",
    },
  },
};

// ── Monokai Pro ────────────────────────────────────────────────────────────
const monokaiPro: Theme = {
  id: "monokai-pro",
  name: "Monokai Pro",
  label: "Monokai",
  swatch: "#2d2a2e",
  colors: {
    bg: "#2d2a2e",
    bgPanel: "#221f22",
    bgTerminal: "#2d2a2e",
    bgHover: "#3a373b",
    bgInput: "#221f22",
    bgSectionHeader: "#302d31",
    border: "#49474c",
    text: "#fcfcfa",
    textMuted: "#c1c0c0",
    textDimmed: "#727072",
    primary: "#ffd866",
    primaryHover: "#e6c25e",
    scrollThumb: "#49474c",
    accent: "#78dce8",
    terminal: {
      background: "#2d2a2e",
      foreground: "#fcfcfa",
      cursor: "#fcfcfa",
      selectionBackground: "#49474c",
      black: "#403e41",
      red: "#ff6188",
      green: "#a9dc76",
      yellow: "#ffd866",
      blue: "#66d9ef",
      magenta: "#ab9df2",
      cyan: "#78dce8",
      white: "#fcfcfa",
      brightBlack: "#727072",
      brightRed: "#ff7b9a",
      brightGreen: "#bdef83",
      brightYellow: "#ffe385",
      brightBlue: "#7ee0f5",
      brightMagenta: "#bfaef7",
      brightCyan: "#8ce7f2",
      brightWhite: "#ffffff",
    },
  },
};

// ── Solarized Light ────────────────────────────────────────────────────────
const solarizedLight: Theme = {
  id: "solarized-light",
  name: "Solarized Light",
  label: "Solarized",
  swatch: "#fdf6e3",
  colors: {
    bg: "#fdf6e3",
    bgPanel: "#eee8d5",
    bgTerminal: "#fdf6e3",
    bgHover: "#e8e1cb",
    bgInput: "#fdf6e3",
    bgSectionHeader: "#f5efdc",
    border: "#d3cbb7",
    text: "#586e75",
    textMuted: "#93a1a1",
    textDimmed: "#b0b8b8",
    primary: "#268bd2",
    primaryHover: "#1e7abc",
    scrollThumb: "#d3cbb7",
    accent: "#2aa198",
    terminal: {
      background: "#fdf6e3",
      foreground: "#586e75",
      cursor: "#586e75",
      selectionBackground: "#eee8d5",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#ea6052",
      brightGreen: "#9eb300",
      brightYellow: "#cfa600",
      brightBlue: "#45a5f1",
      brightMagenta: "#e94b99",
      brightCyan: "#3bc6bb",
      brightWhite: "#fdf6e3",
    },
  },
};

// ── Catppuccin Mocha ──────────────────────────────────────────────────────
const catppuccinMocha: Theme = {
  id: "catppuccin-mocha",
  name: "Catppuccin Mocha",
  label: "Catppuccin",
  swatch: "#1e1e2e",
  colors: {
    bg: "#1e1e2e",
    bgPanel: "#181825",
    bgTerminal: "#1e1e2e",
    bgHover: "#313244",
    bgInput: "#181825",
    bgSectionHeader: "#1a1a2a",
    border: "#45475a",
    text: "#cdd6f4",
    textMuted: "#a6adc8",
    textDimmed: "#6c7086",
    primary: "#cba6f7",
    primaryHover: "#b48bf2",
    scrollThumb: "#45475a",
    accent: "#f5c2e7",
    terminal: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      selectionBackground: "#45475a",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
};

// ── Tokyo Night ───────────────────────────────────────────────────────────
const tokyoNight: Theme = {
  id: "tokyo-night",
  name: "Tokyo Night",
  label: "Tokyo",
  swatch: "#1a1b26",
  colors: {
    bg: "#1a1b26",
    bgPanel: "#16161e",
    bgTerminal: "#1a1b26",
    bgHover: "#292e42",
    bgInput: "#16161e",
    bgSectionHeader: "#1c1d29",
    border: "#3b4261",
    text: "#a9b1d6",
    textMuted: "#737aa2",
    textDimmed: "#565f89",
    primary: "#7aa2f7",
    primaryHover: "#6690e6",
    scrollThumb: "#3b4261",
    accent: "#bb9af7",
    terminal: {
      background: "#1a1b26",
      foreground: "#a9b1d6",
      cursor: "#c0caf5",
      selectionBackground: "#33467c",
      black: "#414868",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#c0caf5",
      brightBlack: "#565f89",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
};

// ── One Dark Pro ──────────────────────────────────────────────────────────
const oneDarkPro: Theme = {
  id: "one-dark-pro",
  name: "One Dark Pro",
  label: "One Dark",
  swatch: "#282c34",
  colors: {
    bg: "#282c34",
    bgPanel: "#21252b",
    bgTerminal: "#282c34",
    bgHover: "#2c313c",
    bgInput: "#21252b",
    bgSectionHeader: "#262a31",
    border: "#3e4451",
    text: "#abb2bf",
    textMuted: "#7f848e",
    textDimmed: "#5c6370",
    primary: "#61afef",
    primaryHover: "#519fd9",
    scrollThumb: "#3e4451",
    accent: "#c678dd",
    terminal: {
      background: "#282c34",
      foreground: "#abb2bf",
      cursor: "#528bff",
      selectionBackground: "#3e4451",
      black: "#3f4451",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#5c6370",
      brightRed: "#be5046",
      brightGreen: "#98c379",
      brightYellow: "#d19a66",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#e6e6e6",
    },
  },
};

// ── Rosé Pine ─────────────────────────────────────────────────────────────
const rosePine: Theme = {
  id: "rose-pine",
  name: "Rosé Pine",
  label: "Rosé Pine",
  swatch: "#191724",
  colors: {
    bg: "#191724",
    bgPanel: "#1f1d2e",
    bgTerminal: "#191724",
    bgHover: "#26233a",
    bgInput: "#1f1d2e",
    bgSectionHeader: "#1d1a2b",
    border: "#403d52",
    text: "#e0def4",
    textMuted: "#908caa",
    textDimmed: "#6e6a86",
    primary: "#c4a7e7",
    primaryHover: "#b195d9",
    scrollThumb: "#403d52",
    accent: "#ebbcba",
    terminal: {
      background: "#191724",
      foreground: "#e0def4",
      cursor: "#524f67",
      selectionBackground: "#2a283e",
      black: "#26233a",
      red: "#eb6f92",
      green: "#31748f",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ebbcba",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#eb6f92",
      brightGreen: "#31748f",
      brightYellow: "#f6c177",
      brightBlue: "#9ccfd8",
      brightMagenta: "#c4a7e7",
      brightCyan: "#ebbcba",
      brightWhite: "#e0def4",
    },
  },
};

// ── Gruvbox Dark ──────────────────────────────────────────────────────────
const gruvboxDark: Theme = {
  id: "gruvbox-dark",
  name: "Gruvbox Dark",
  label: "Gruvbox",
  swatch: "#282828",
  colors: {
    bg: "#282828",
    bgPanel: "#1d2021",
    bgTerminal: "#282828",
    bgHover: "#3c3836",
    bgInput: "#1d2021",
    bgSectionHeader: "#252525",
    border: "#504945",
    text: "#ebdbb2",
    textMuted: "#a89984",
    textDimmed: "#7c6f64",
    primary: "#fabd2f",
    primaryHover: "#e5ab27",
    scrollThumb: "#504945",
    accent: "#8ec07c",
    terminal: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      selectionBackground: "#504945",
      black: "#3c3836",
      red: "#fb4934",
      green: "#b8bb26",
      yellow: "#fabd2f",
      blue: "#83a598",
      magenta: "#d3869b",
      cyan: "#8ec07c",
      white: "#d5c4a1",
      brightBlack: "#665c54",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#fbf1c7",
    },
  },
};

// ── GitHub Light ──────────────────────────────────────────────────────────
const githubLight: Theme = {
  id: "github-light",
  name: "GitHub Light",
  label: "GitHub Lt",
  swatch: "#ffffff",
  colors: {
    bg: "#ffffff",
    bgPanel: "#f6f8fa",
    bgTerminal: "#ffffff",
    bgHover: "#eef1f5",
    bgInput: "#f6f8fa",
    bgSectionHeader: "#f0f3f6",
    border: "#d1d9e0",
    text: "#1f2328",
    textMuted: "#656d76",
    textDimmed: "#8b949e",
    primary: "#0969da",
    primaryHover: "#0550ae",
    scrollThumb: "#c8ccd1",
    accent: "#1a7f37",
    terminal: {
      background: "#ffffff",
      foreground: "#1f2328",
      cursor: "#1f2328",
      selectionBackground: "#b6e3ff",
      black: "#1f2328",
      red: "#cf222e",
      green: "#116329",
      yellow: "#9a6700",
      blue: "#0969da",
      magenta: "#8250df",
      cyan: "#1b7c83",
      white: "#6e7781",
      brightBlack: "#57606a",
      brightRed: "#a40e26",
      brightGreen: "#1a7f37",
      brightYellow: "#7d4e00",
      brightBlue: "#218bff",
      brightMagenta: "#a475f9",
      brightCyan: "#3192aa",
      brightWhite: "#8c959f",
    },
  },
};

// ── Catppuccin Latte ─────────────────────────────────────────────────────
const catppuccinLatte: Theme = {
  id: "catppuccin-latte",
  name: "Catppuccin Latte",
  label: "Catppuccin Lt",
  swatch: "#eff1f5",
  colors: {
    bg: "#eff1f5",
    bgPanel: "#e6e9ef",
    bgTerminal: "#eff1f5",
    bgHover: "#dce0e8",
    bgInput: "#e6e9ef",
    bgSectionHeader: "#e8ebf0",
    border: "#ccd0da",
    text: "#4c4f69",
    textMuted: "#6c6f85",
    textDimmed: "#9ca0b0",
    primary: "#8839ef",
    primaryHover: "#7528d4",
    scrollThumb: "#bcc0cc",
    accent: "#ea76cb",
    terminal: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      selectionBackground: "#ccd0da",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
};

// ── Rosé Pine Dawn ───────────────────────────────────────────────────────
const rosePineDawn: Theme = {
  id: "rose-pine-dawn",
  name: "Rosé Pine Dawn",
  label: "Rosé Dawn",
  swatch: "#faf4ed",
  colors: {
    bg: "#faf4ed",
    bgPanel: "#fffaf3",
    bgTerminal: "#faf4ed",
    bgHover: "#f2e9de",
    bgInput: "#fffaf3",
    bgSectionHeader: "#f4ede5",
    border: "#dfdad9",
    text: "#575279",
    textMuted: "#797593",
    textDimmed: "#9893a5",
    primary: "#907aa9",
    primaryHover: "#7d6899",
    scrollThumb: "#cecacd",
    accent: "#d7827e",
    terminal: {
      background: "#faf4ed",
      foreground: "#575279",
      cursor: "#575279",
      selectionBackground: "#dfdad9",
      black: "#575279",
      red: "#b4637a",
      green: "#286983",
      yellow: "#ea9d34",
      blue: "#56949f",
      magenta: "#907aa9",
      cyan: "#d7827e",
      white: "#e0def4",
      brightBlack: "#797593",
      brightRed: "#b4637a",
      brightGreen: "#286983",
      brightYellow: "#ea9d34",
      brightBlue: "#56949f",
      brightMagenta: "#907aa9",
      brightCyan: "#d7827e",
      brightWhite: "#f2e9de",
    },
  },
};

// ── Nord Light ────────────────────────────────────────────────────────────
const nordLight: Theme = {
  id: "nord-light",
  name: "Nord Light",
  label: "Nord Lt",
  swatch: "#eceff4",
  colors: {
    bg: "#eceff4",
    bgPanel: "#e5e9f0",
    bgTerminal: "#eceff4",
    bgHover: "#d8dee9",
    bgInput: "#e5e9f0",
    bgSectionHeader: "#e8ecf1",
    border: "#c9cfda",
    text: "#2e3440",
    textMuted: "#4c566a",
    textDimmed: "#7b88a1",
    primary: "#5e81ac",
    primaryHover: "#4e6f96",
    scrollThumb: "#c0c7d3",
    accent: "#88c0d0",
    terminal: {
      background: "#eceff4",
      foreground: "#2e3440",
      cursor: "#2e3440",
      selectionBackground: "#d8dee9",
      black: "#2e3440",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#5e81ac",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#d8dee9",
      brightBlack: "#4c566a",
      brightRed: "#d06f79",
      brightGreen: "#b1cc99",
      brightYellow: "#f1d59d",
      brightBlue: "#81a1c1",
      brightMagenta: "#c59cbd",
      brightCyan: "#9bd3e4",
      brightWhite: "#eceff4",
    },
  },
};

// ── One Light ─────────────────────────────────────────────────────────────
const oneLight: Theme = {
  id: "one-light",
  name: "One Light",
  label: "One Light",
  swatch: "#fafafa",
  colors: {
    bg: "#fafafa",
    bgPanel: "#f0f0f0",
    bgTerminal: "#fafafa",
    bgHover: "#e5e5e6",
    bgInput: "#f0f0f0",
    bgSectionHeader: "#f2f2f2",
    border: "#dbdbdc",
    text: "#383a42",
    textMuted: "#696c77",
    textDimmed: "#a0a1a7",
    primary: "#4078f2",
    primaryHover: "#2f65de",
    scrollThumb: "#c4c4c5",
    accent: "#a626a4",
    terminal: {
      background: "#fafafa",
      foreground: "#383a42",
      cursor: "#526eff",
      selectionBackground: "#e5e5e6",
      black: "#383a42",
      red: "#e45649",
      green: "#50a14f",
      yellow: "#c18401",
      blue: "#4078f2",
      magenta: "#a626a4",
      cyan: "#0184bc",
      white: "#a0a1a7",
      brightBlack: "#696c77",
      brightRed: "#ca1243",
      brightGreen: "#50a14f",
      brightYellow: "#c18401",
      brightBlue: "#4078f2",
      brightMagenta: "#a626a4",
      brightCyan: "#0184bc",
      brightWhite: "#c4c4c5",
    },
  },
};

// ── Exports ────────────────────────────────────────────────────────────────

export const themes: Record<string, Theme> = {
  "github-dark": githubDark,
  dracula,
  nord,
  "monokai-pro": monokaiPro,
  "solarized-light": solarizedLight,
  "catppuccin-mocha": catppuccinMocha,
  "tokyo-night": tokyoNight,
  "one-dark-pro": oneDarkPro,
  "rose-pine": rosePine,
  "gruvbox-dark": gruvboxDark,
  "github-light": githubLight,
  "catppuccin-latte": catppuccinLatte,
  "rose-pine-dawn": rosePineDawn,
  "nord-light": nordLight,
  "one-light": oneLight,
};

export const themeList: Theme[] = [
  githubDark,
  dracula,
  nord,
  monokaiPro,
  solarizedLight,
  catppuccinMocha,
  tokyoNight,
  oneDarkPro,
  rosePine,
  gruvboxDark,
  githubLight,
  catppuccinLatte,
  rosePineDawn,
  nordLight,
  oneLight,
];

export const DEFAULT_THEME_ID = "github-dark";
